name: Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: latest

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build extension
      run: pnpm run build

    - name: Set version variable
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        else
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        fi

    - name: Create zip package
      run: |
        cd dist
        zip -r ../notion2wechat-v${{ env.VERSION }}.zip .
        cd ..

    - name: Upload zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-zip
        path: notion2wechat-v*.zip
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: extension-zip

    - name: List files
      run: ls -la

    - name: Upload release assets
      uses: softprops/action-gh-release@v2.3.4
      with:
        files: |
          notion2wechat-v${{ github.event.release.tag_name }}.zip
        overwrite: true
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}